server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: smartgo-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:smartgo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    clean-disabled: true
    baseline-on-migrate: true
    baseline-version: 0

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Custom JWT configuration
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:3cfa76a263884b6f79024f2b3e8e2c0ad19a7cfd7a6e138a081a95b8efc8f386}
      # 2 hours token validity in milliseconds (7200000 ms)
      expiration: ${JWT_EXPIRATION:7200000}

# Springdoc Swagger configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    tagsSorter: alpha

logging:
  level:
    root: INFO
    com.smartgo: DEBUG
    org.springframework.security: INFO
